shellEmulator: true
patchedDependencies:
  glyphhanger@5.0.0: patches/glyphhanger@5.0.0.patch
  '@zachleat/spider-pig@3.0.0': patches/@zachleat__spider-pig@3.0.0.patch
  panzoom: patches/panzoom.patch
allowBuilds:
  '@tailwindcss/oxide': true
  esbuild: true
  gifsicle: true
  jpegtran-bin: true
  optipng-bin: true
  puppeteer: true
  sharp: true
  unrs-resolver: true
