allowBuilds:
  '@tailwindcss/oxide': true
  esbuild: true
  puppeteer: true
  sharp: true
  unrs-resolver: true
  workerd: true
patchedDependencies:
  glyphhanger@6.0.0: patches/glyphhanger@6.0.0.patch
  'panzoom': patches/panzoom.patch
shellEmulator: true
overrides:
  'uuid@<11.1.1': ^11.1.1
