name: Deploy

on:
  push:
    branches: [main]

concurrency:
  # Ensure only a single deployment occurs at any given time.
  group: deploy
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Install Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24

      - name: Install pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          version: 11
          cache: true
          run_install: true

      # For glyphhanger
      - name: Install fonttools
        run: pip3 install fonttools[woff]

      - name: Build
        run: pnpm build
        env:
          SITE_URL: https://tomeraberba.ch
          FONTCONFIG_PATH: private/fonts
          PANGOCAIRO_BACKEND: fontconfig

      - name: Deploy
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          packageManager: pnpm
