name: Optimize Images

on:
  pull_request:
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'

jobs:
  run:
    # Only run on pull requests within the same repository, and not from forks
    if: github.event.pull_request.head.repo.full_name == github.repository
    name: Optimize Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Optimize Images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
